name: Agenda Paroquial

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  executar:
    runs-on: ubuntu-latest

    steps:

    - name: Baixar repositorio
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependencias
      run: pip install -r requirements.txt

    - name: Gerar agenda Google
      run: python gerar_calendar.py

    - name: Gerar PDF
      run: python gerar_pdf.py

    - name: Executar bot
      run: python main.py
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
